name: Build and Publish Docs

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

permissions:
  contents: write
  pages: write

jobs:
  build-docs:
    name: Build Doxygen Docs
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Doxygen and Graphviz
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Configure CMake (Docs)
        run: cmake -S . -B build -DBUILD_DOC=ON

      - name: Build documentation
        run: cmake --build build --target build_documentation

      - name: Upload documentation to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/docs/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4