name: Build and Publish Docs

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    name: Build Doxygen Docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/vcpkg
            ${{ github.workspace }}/.vcpkg
          key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-

      - name: Install dependencies via vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'
          runVcpkgInstall: true
          vcpkgDirectory: '${{ github.workspace }}/.vcpkg'

      - name: Install Doxygen and Graphviz
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Configure CMake (Docs)
        run: cmake -S . -B build -DBUILD_DOC=ON -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake

      - name: Build documentation
        run: cmake --build build --target build_documentation

      - name: Upload documentation to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/docs/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4