name: Build and Publish Docs

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  build-docs:
    name: Build Doxygen Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Configure CMake
        run: cmake -S . -B build -DBUILD_DOC=ON

      - name: Build documentation
        run: cmake --build build --target doc

      - name: Upload generated docs as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-docs
          path: build/docs/html

      - name: Deploy to GitHub Pages (main branch only)
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/docs/html