name: Build and Publish Docs

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  build-docs:
    name: Build Doxygen Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies via vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'
          runVcpkgInstall: true
          vcpkgDirectory: '${{ github.workspace }}/.vcpkg'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Configure CMake
        run: cmake -S . -B build -DBUILD_DOC=ON -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake

      - name: Build documentation
        run: cmake --build build --target build_documentation

      - name: Copy docs to publish folder
        run: |
          mkdir -p ghpages
          cp -r build/docs/html/* ghpages/

      - name: Deploy to gh-pages branch
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ghpages
          publish_branch: gh-pages
          force_orphan: true
          enable_jekyll: false
